version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: firebase-tools
    versions:
    - 9.7.0
  - dependency-name: next-i18next
    versions:
    - 8.0.3
    - 8.1.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.27
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
  - dependency-name: ini
    versions:
    - 1.3.8
